#!/bin/bash

echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
PACKAGE_BASE=${TRIM_APPDEST}
EXEC_BIN="${PACKAGE_BASE}/app/node_exporter"
#EXEC_ARGS=" --collector.processes --collector.interrupts --collector.wifi --collector.tcpstat"
EXEC_ARGS="  --collector.rapl.enable-zone-label"
LOG_FILE="/var/log/node_exporter.log"
#LOCKFILE="/var/lock/subsys/node_exporter"

EXEC_CMDLINE="${EXEC_BIN} ${EXEC_ARGS}"

case $1 in
start)
	processNum=$(pgrep -c node_exporter)
	if [[ ! $processNum -eq 0 ]]; then
		echo "is already running"
		exit 0
	else
		if modprobe -v drivetemp;then
		  echo "load drivetemp succ"
		else
		  echo "load drivetemp fail"
		fi

		CPU_COUNT=$(nproc)
    BIND_COUNT=4
    [ "$CPU_COUNT" -lt "$BIND_COUNT" ] && BIND_COUNT="$CPU_COUNT"
    START_CPU=$((CPU_COUNT - BIND_COUNT))
    CPU_LIST=""
    for i in $(seq 0 $((BIND_COUNT - 1))); do
				CPU_LIST="${CPU_LIST}$((START_CPU + i)),"
    done
    CPU_LIST=${CPU_LIST%,}

		echo "taskset -c ${CPU_LIST} ${EXEC_CMDLINE}"
		echo -e "$(date +'%Y/%m/%d %H:%M:%S') clear log" > ${LOG_FILE}
		nohup taskset -c ${CPU_LIST} ${EXEC_CMDLINE} >>${LOG_FILE} 2>&1 &
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
			exit 0
		else
			exit 1
		fi
	fi
	;;
stop)
	pkill -9 node_exporter || echo "pkill fail $?"
	;;
status)
	processNum=$(pgrep -c node_exporter)
	if [[ ! $processNum -eq 0 ]]; then
		echo "is already running"
		exit 0
	else
		exit 3
	fi
	;;
*)
	exit 1
	;;
esac