#!/bin/bash

echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
PACKAGE_BASE=${TRIM_APPDEST}
EXEC_BIN="${PACKAGE_BASE}/app/node_exporter"
#EXEC_ARGS=" --collector.processes --collector.interrupts --collector.wifi --collector.tcpstat"
EXEC_ARGS=" "
LOG_FILE="/var/log/node_exporter.log"
#LOCKFILE="/var/lock/subsys/node_exporter"

EXEC_CMDLINE="${EXEC_BIN} ${EXEC_ARGS}"

case $1 in
start)
	processNum=$(ps -fe | grep app/node_exporter | grep -v grep | grep -v tail | wc -l)
	if [[ ! $processNum -eq 0 ]]; then
		echo "is already running"
		exit 0
	else
		CPU_COUNT=$(nproc)
		CPU1=$((CPU_COUNT - 1))
		CPU2=$((CPU_COUNT - 2))
		CPU3=$((CPU_COUNT - 3))
		CPU4=$((CPU_COUNT - 4))
		if [ "$CPU2" -lt 0 ]; then
			CPU2=0
		fi
		if [ "$CPU3" -lt 0 ]; then
			CPU3=0
		fi
		if [ "$CPU4" -lt 0 ]; then
			CPU4=0
		fi
		echo "taskset -c ${CPU1},${CPU2},${CPU3},${CPU4} ${EXEC_CMDLINE}"
		nohup taskset -c ${CPU1},${CPU2},${CPU3},${CPU4} ${EXEC_CMDLINE} >>${LOG_FILE} 2>&1 &
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
			exit 0
		else
			exit 1
		fi
	fi
	;;
stop)
	pkill -9 node_exporter
	;;
status)
	processNum=$(ps -fe | grep app/node_exporter | grep -v grep | grep -v tail | wc -l)
	if [[ ! $processNum -eq 0 ]]; then
		echo "is already running"
		exit 0
	else
		exit 3
	fi
	;;
*)
	exit 1
	;;
esac